### PR TITLE
Support custom DBPath

### PR DESCRIPTION
**Pull request by ilpianista**
Parses /etc/pacman.conf and reads DBPath if set.

### CODE REVIEW

**Comment by dns2utf8** [comment]
Cool :smiley: 

Would you mind refactoring the read out to a function or use [rust-ini](https://crates.io/crates/rust-ini)

**Comment by dns2utf8** [comment]
I noticed travis did not check you branch, so I fixed it but would you have to rebase it to use it.

**Comment by djmattyg007** [comment]
Parsing `pacman.conf` manually is a rather brittle way of accessing pacman's configuration. The `pacconf` utility (which comes with pacman) should be used, as it also correctly accounts for any `Include` directives that may be in any of its configuration files.

**Comment by dns2utf8** [comment]
Thank you! Can you implement it in a seperate PR?

**Comment by dns2utf8** [comment]
I searched `alpm.h` and I were unable to find a configuration reader, is it implemented in pacman directly?

**Comment by ilpianista** [comment]
Thank you @djmattyg007 for your suggestion.
@dns2utf8 yes, it's directly in pacman. Then I suppose alpm-rs should defaults to `/var/lib/pacman` and allows to re-define it. e.g. by adding a `set_dbpath()` or by taking it as argument of `new()`.

**Comment by dns2utf8** [comment]
The user must not bet able to change the dbpath while the handler is valid. 
So I would prefere a method like `with_dbpath(p: Into<String>) -> Alpm` or the `extract_db_path()` should follow the `Include = ...` directives.

What do you think?

**Comment by ilpianista** [comment]
Ah right. Ok then `with_dbpath(p: Into<String>) -> Alpm` is fine.

Just wondering, why not exposing another constructor with `new(p: Into<String>) -> Alpm`?

**Comment by dns2utf8** [comment]
Beacause rust does not have overloads. `pub fn with_dbpath(p: Into<String>) -> Alpm` would be a second constructor function.

The `pub fn new() -> Alpm` could use it with the default path.

**Comment by ilpianista** [comment]
Thanks for the explanation. Go for `with_dbpath` then! :-)

**Comment by djmattyg007** [comment]
I am not a C or Rust developer, and have no knowledge of what is or isn't exposed through pacman's C APIs. I'm just a concerned bystander hoping to make the world a better place!

**Comment by dns2utf8** [comment]
Done, released as 0.3.0.
Do you know if the Arch devs were interested in migrating pacman to Rust?

**Comment by ilpianista** [comment]
Great!

Nope, I don't think they will :-)

**Pull request merged**
